# This is a basic workflow to help you get started with Actions
name: CI

on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          ./script.sh

          echo "Comment on PR #${{ toJSON(github) }}"
